const doctorDiagnoses = [
  { patientCode: "PAT-JGT-001", disease: "Dengue" },
  { patientCode: "PAT-JGT-002", disease: "Dengue" },
  { patientCode: "PAT-JGT-003", disease: "Malaria" },
  { patientCode: "PAT-JGT-004", disease: "Dengue" },
  { patientCode: "PAT-JGT-005", disease: "Viral Fever" },
  { patientCode: "PAT-JGT-006", disease: "Dengue" },
  { patientCode: "PAT-JGT-007", disease: "Dengue" },
  { patientCode: "PAT-JGT-008", disease: "Malaria" },
  { patientCode: "PAT-JGT-009", disease: "Malaria" },
  { patientCode: "PAT-JGT-010", disease: "Dengue" },
  { patientCode: "PAT-JGT-011", disease: "Dengue" },
  { patientCode: "PAT-JGT-012", disease: "Dengue" },
  { patientCode: "PAT-JGT-013", disease: "Malaria" },
  { patientCode: "PAT-JGT-014", disease: "Viral Fever" },
  { patientCode: "PAT-JGT-015", disease: "Dengue" },
  { patientCode: "PAT-JGT-016", disease: "Malaria" },
  { patientCode: "PAT-JGT-017", disease: "Malaria" },
  { patientCode: "PAT-JGT-018", disease: "Dengue" },
  { patientCode: "PAT-JGT-019", disease: "Dengue" },
  { patientCode: "PAT-JGT-020", disease: "Viral Fever" },
  { patientCode: "PAT-JGT-021", disease: "Dengue" },
  { patientCode: "PAT-JGT-022", disease: "Dengue" },
  { patientCode: "PAT-JGT-023", disease: "Malaria" },
  { patientCode: "PAT-JGT-024", disease: "Dengue" },
  { patientCode: "PAT-JGT-025", disease: "Dengue" },
  { patientCode: "PAT-JGT-026", disease: "Viral Fever" },
  { patientCode: "PAT-JGT-027", disease: "Dengue" },
  { patientCode: "PAT-JGT-028", disease: "Dengue" },
  { patientCode: "PAT-JGT-029", disease: "Dengue" },
  { patientCode: "PAT-JGT-030", disease: "Viral Fever" },
  { patientCode: "PAT-JGT-031", disease: "Dengue" },
  { patientCode: "PAT-JGT-032", disease: "Dengue" },
  { patientCode: "PAT-JGT-033", disease: "Dengue" },
  { patientCode: "PAT-JGT-034", disease: "Malaria" },
  { patientCode: "PAT-JGT-035", disease: "Dengue" },
  { patientCode: "PAT-JGT-036", disease: "Malaria" },
  { patientCode: "PAT-JGT-037", disease: "Dengue" },
  { patientCode: "PAT-JGT-038", disease: "Dengue" },
  { patientCode: "PAT-JGT-039", disease: "Dengue" },
  { patientCode: "PAT-JGT-040", disease: "Viral Fever" },
  { patientCode: "PAT-JGT-041", disease: "Dengue" },
  { patientCode: "PAT-JGT-042", disease: "Dengue" },
  { patientCode: "PAT-JGT-043", disease: "Malaria" },
  { patientCode: "PAT-JGT-044", disease: "Dengue" },
  { patientCode: "PAT-JGT-045", disease: "Dengue" },
  { patientCode: "PAT-JGT-046", disease: "Dengue" },
  { patientCode: "PAT-JGT-047", disease: "Dengue" },
  { patientCode: "PAT-JGT-048", disease: "Dengue" },
  { patientCode: "PAT-JGT-049", disease: "Malaria" },
  { patientCode: "PAT-JGT-050", disease: "Dengue" }
];

module.exports = { doctorDiagnoses };
